name: grocery
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/

  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/gilory_bold.ttf
          weight: 700
        - asset: assets/fonts/gilory_medium.ttf
          weight: 600
        - asset: assets/fonts/gilory_medium.ttf
          weight: 500
        - asset: assets/fonts/gilory_light.otf
          weight: 400
        - asset: assets/fonts/gilory_light.otf
          weight: 300
